ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - name: Development Environment
    init: |
      composer install
      cd build/
      npm i
    command: php -S 0.0.0.0:8000 -t /

vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client
